# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cec41304e73ec02fb427506ef19429596d6d7738168aa3932f7f86cca583f94cc1efa6b6ab61c8168c77f7aaba443027e3cda24307ceb9e94a0b6b315860ff62

test:
  secret_key_base: b4c5693171e7f7b58d266ceb22ae3c9906c4e6b86848ec8d2b32d09eebc771d7877668feb06f7935496633827b27185814588c07d3454907da6ae67a47537071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
